app:
  name: "web_app"
  mode: "release"
  port: 8081
log:
  level: "warn"
  filename: "web_app_log.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: mysql80
  user: "root"
  password: 142212
  port: 3306
  dbname: "jokeweb"
  max_conn: 200
  max_idle_conns: 10
redis:
  host: redis507
  port: 6379
  password: ""
  db: 0
  poolsize: 100
es:
  host: elastic7.8
  port: 9200
auth:
  jwt_expire: 2